# serverless.yml
service: phpLayers
frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  region: eu-west-1
layers:
  php73:
    path: layer/php
    name: ${self:provider.stage}-php73
    description: Provides a PHP 7.3 runtime
